// English Practice — Question Bank
// Each question: { id, type: 'vocab'|'phrase'|'grammar', cat: 'daily'|'travel', text, correct, distractors: [3], ex }
// "text" uses ___ as the blank. "correct" + "distractors" are combined and shuffled at runtime.
// To add more questions later: just append objects with a new unique id.

export const QUESTIONS = [
  // ---------- Original set (1-40) ----------
  {id:1, type:"phrase", cat:"daily", text:"Could you ___ me a favor and pick up some milk on your way home?", correct:"do", distractors:["take","give","make"], ex:"請人幫忙的固定搭配是 do me a favor，不能用 make / give / take。"},
  {id:2, type:"phrase", cat:"travel", text:"Excuse me, do you have anything to ___ at customs?", correct:"declare", distractors:["say","announce","tell"], ex:"海關常用語 anything to declare，表示「需要申報的物品」。"},
  {id:3, type:"grammar", cat:"daily", text:"I'm sorry I'm late — something urgent ___ up at the last minute.", correct:"has come", distractors:["came","comes","come"], ex:"強調對現在造成的影響，要用現在完成式 has come up。"},
  {id:4, type:"phrase", cat:"travel", text:"I'd like to check ___ now. Here's my passport and reservation.", correct:"in", distractors:["on","up","at"], ex:"飯店「辦理入住」的固定用法是 check in。"},
  {id:5, type:"phrase", cat:"daily", text:"Could you keep ___ on my bag while I use the restroom?", correct:"an eye", distractors:["a look","a watch","a sight"], ex:"「幫忙看著東西」的慣用語是 keep an eye on something。"},
  {id:6, type:"grammar", cat:"travel", text:"Is breakfast ___ in the room rate, or is it extra?", correct:"included", distractors:["include","includes","including"], ex:"be 動詞 + 過去分詞構成被動語態，表示「被包含在內」。"},
  {id:7, type:"grammar", cat:"daily", text:"I haven't seen you ___ ages! How have you been?", correct:"for", distractors:["since","from","in"], ex:"現在完成式搭配一段時間長度用 for，搭配明確時間點才用 since。"},
  {id:8, type:"grammar", cat:"travel", text:"Excuse me, which platform does the train to Queenstown ___ from?", correct:"leave", distractors:["leaves","leaving","left"], ex:"句中已有助動詞 does，後面動詞要還原成原形 leave。"},
  {id:9, type:"phrase", cat:"daily", text:"Sorry, could you say that again? I didn't quite ___ it.", correct:"catch", distractors:["get","hold","keep"], ex:"「沒聽清楚」的口語說法是 catch what someone said。"},
  {id:10, type:"phrase", cat:"travel", text:"We're fully booked tonight, but I can put you ___ the waiting list.", correct:"on", distractors:["in","at","to"], ex:"「列入候補名單」的固定搭配是 put someone on the waiting list。"},
  {id:11, type:"vocab", cat:"daily", text:"He's been feeling under the weather, so he stayed home today. What does 'under the weather' mean?", correct:"Sick", distractors:["Tired","Busy","Sad"], ex:"under the weather 是常見口語，意思是「身體不舒服」。"},
  {id:12, type:"grammar", cat:"travel", text:"Could you recommend a local dish that's especially ___ around here?", correct:"popular", distractors:["popularity","populate","popularly"], ex:"需要形容詞修飾名詞 dish，故選 popular。"},
  {id:13, type:"phrase", cat:"daily", text:"I can't talk right now — can I call you ___ in ten minutes?", correct:"back", distractors:["again","later","return"], ex:"「回電」的固定用法是 call someone back。"},
  {id:14, type:"grammar", cat:"travel", text:"How long does it ___ to get to the airport from downtown?", correct:"take", distractors:["spend","cost","need"], ex:"詢問花費時間用句型 it takes + 時間，spend 的主詞須是人。"},
  {id:15, type:"phrase", cat:"daily", text:"Don't worry about the bill — it's ___ me this time.", correct:"on", distractors:["in","for","to"], ex:"「這次我請客」的口語說法是 It's on me。"},
  {id:16, type:"vocab", cat:"travel", text:"Is this seat taken, or is it ___?", correct:"free", distractors:["empty","vacant","alone"], ex:"詢問座位是否有人坐，口語常用 Is this seat free?"},
  {id:17, type:"phrase", cat:"daily", text:"I've been meaning to call you, but I just haven't ___ around to it.", correct:"got", distractors:["gone","come","made"], ex:"get around to + N/Ving 表示「終於抽空做某事」。"},
  {id:18, type:"phrase", cat:"travel", text:"Could you tell me how to ___ to the nearest pharmacy?", correct:"get", distractors:["go","walk","reach"], ex:"問路常用句型 How to get to + 地點。"},
  {id:19, type:"grammar", cat:"daily", text:"She's really good ___ dealing with difficult customers.", correct:"at", distractors:["in","for","with"], ex:"be good at + Ving 表示「擅長於」。"},
  {id:20, type:"phrase", cat:"travel", text:"We got caught ___ in traffic and missed our connecting flight.", correct:"up", distractors:["in","on","at"], ex:"get caught up in traffic 表示「被困在車陣中」。"},
  {id:21, type:"grammar", cat:"daily", text:"Could you turn the volume down? It's a bit ___ loud.", correct:"too", distractors:["so","very","much"], ex:"too + 形容詞表示「過於」，帶有負面語氣，符合語境。"},
  {id:22, type:"vocab", cat:"travel", text:"Excuse me, is there a currency exchange ___ here in the airport?", correct:"nearby", distractors:["near","close","closely"], ex:"nearby 可直接修飾地點，表示「附近的」。"},
  {id:23, type:"phrase", cat:"daily", text:"I'm trying to cut ___ on sugar, so I'll skip dessert.", correct:"down", distractors:["off","out","up"], ex:"cut down on + N 表示「減少攝取」。"},
  {id:24, type:"grammar", cat:"travel", text:"The flight has been delayed ___ to bad weather.", correct:"due", distractors:["owing","because","caused"], ex:"due to + 名詞表示「由於」。"},
  {id:25, type:"grammar", cat:"daily", text:"He apologized ___ being late to the meeting.", correct:"for", distractors:["to","about","of"], ex:"apologize for + N/Ving 表示「為某事道歉」。"},
  {id:26, type:"phrase", cat:"travel", text:"Could I have a window seat ___ possible?", correct:"if", distractors:["when","as","in"], ex:"if possible 是常見插入語，表示「如果可以的話」。"},
  {id:27, type:"grammar", cat:"daily", text:"I'm looking forward ___ seeing you next week.", correct:"to", distractors:["for","on","at"], ex:"look forward to + Ving，這裡的 to 是介系詞而非不定詞。"},
  {id:28, type:"phrase", cat:"travel", text:"Sorry, I'm a bit lost — could you point me ___ the right direction?", correct:"in", distractors:["to","at","on"], ex:"point someone in the right direction 是固定片語，表示「指引方向」。"},
  {id:29, type:"phrase", cat:"daily", text:"It's been raining ___ and off all day.", correct:"on", distractors:["off","in","at"], ex:"on and off 表示「斷斷續續」。"},
  {id:30, type:"grammar", cat:"travel", text:"Could you let me know ___ the bus arrives?", correct:"once", distractors:["until","while","during"], ex:"once 在此作連接詞，表示「一旦…」。"},
  {id:31, type:"grammar", cat:"daily", text:"I'd rather you ___ smoke in here, if that's okay.", correct:"didn't", distractors:["don't","won't","not"], ex:"would rather + 主詞 + 過去式動詞，是委婉的請求或建議句型。"},
  {id:32, type:"grammar", cat:"travel", text:"Do you know of any good restaurants ___ within walking distance?", correct:"that are", distractors:["which is","who are","what are"], ex:"先行詞 restaurants 為複數，關代子句動詞需用 are，指物用 that/which。"},
  {id:33, type:"phrase", cat:"daily", text:"I haven't decided yet — I'm still weighing ___ my options.", correct:"up", distractors:["on","in","for"], ex:"weigh up one's options 表示「仔細考慮各種選擇」。"},
  {id:34, type:"phrase", cat:"travel", text:"Make sure you keep your passport with you at ___ times.", correct:"all", distractors:["the","any","every"], ex:"at all times 是固定片語，表示「隨時、一直」。"},
  {id:35, type:"grammar", cat:"daily", text:"I can't believe how time flies — it feels ___ yesterday that we graduated.", correct:"like", distractors:["as","such","so"], ex:"feel like + 子句，表示「感覺像是…」。"},
  {id:36, type:"grammar", cat:"travel", text:"The tour guide told us to meet ___ the lobby at 8 a.m. sharp.", correct:"in", distractors:["at","on","to"], ex:"在室內空間（大廳）用介系詞 in。"},
  {id:37, type:"phrase", cat:"daily", text:"Could you give me a hand ___ these boxes? They're really heavy.", correct:"with", distractors:["for","to","of"], ex:"give someone a hand with + N，表示「幫忙做某事」。"},
  {id:38, type:"phrase", cat:"travel", text:"We should book the hotel ___ advance to get a better rate.", correct:"in", distractors:["on","at","by"], ex:"in advance 表示「提前」。"},
  {id:39, type:"phrase", cat:"daily", text:"He's not much ___ a cook, but he tries his best.", correct:"of", distractors:["as","for","like"], ex:"not much of a + N 表示「算不上是…」，是常見口語句型。"},
  {id:40, type:"grammar", cat:"travel", text:"Let's ask the front desk if they can arrange a taxi ___ us.", correct:"for", distractors:["to","with","of"], ex:"arrange something for someone 表示「為某人安排某事」。"},

  // ---------- Grammar batch (41-80) ----------
  {id:41, type:"grammar", cat:"daily", text:"She has lived in Taipei ___ she was born.", correct:"since", distractors:["for","during","while"], ex:"since + 時間點，表示「從某個時間點開始」；for + 一段時間長度。"},
  {id:42, type:"grammar", cat:"travel", text:"If it ___ tomorrow, we'll just visit the museum instead.", correct:"rains", distractors:["will rain","rained","is raining"], ex:"第一類條件句：if 子句用現在簡單式，主句才用 will。"},
  {id:43, type:"grammar", cat:"daily", text:"I wish I ___ more time to relax these days.", correct:"had", distractors:["have","will have","having"], ex:"wish + 過去式表達對現在的不滿或假設，用過去簡單式。"},
  {id:44, type:"grammar", cat:"travel", text:"By the time we arrived at the gate, the plane ___ already.", correct:"had left", distractors:["left","has left","was leaving"], ex:"過去完成式表示在過去某個時間點之前已完成的動作。"},
  {id:45, type:"grammar", cat:"daily", text:"He suggested ___ a different route to avoid traffic.", correct:"taking", distractors:["to take","take","took"], ex:"suggest + Ving，不能接 to V。"},
  {id:46, type:"grammar", cat:"travel", text:"This is the hotel ___ we stayed last summer.", correct:"where", distractors:["which","that","when"], ex:"先行詞是地點，關係副詞用 where。"},
  {id:47, type:"grammar", cat:"daily", text:"There ___ a lot of traffic on the highway this morning.", correct:"was", distractors:["were","is","are"], ex:"traffic 是不可數名詞，動詞要用單數 was。"},
  {id:48, type:"grammar", cat:"travel", text:"Could you tell me ___ the museum opens?", correct:"what time", distractors:["what time does","when does","what time is"], ex:"間接問句語序是「疑問詞+主詞+動詞」，不能用一般問句的倒裝。"},
  {id:49, type:"grammar", cat:"daily", text:"I'm used ___ early for work every day.", correct:"to getting up", distractors:["to get up","getting up","get up"], ex:"be used to + Ving 表示「已經習慣於」。"},
  {id:50, type:"grammar", cat:"travel", text:"The longer we waited, ___ we got.", correct:"the more impatient", distractors:["more impatient","the most impatient","much more impatient"], ex:"the + 比較級, the + 比較級，表示「越…就越…」。"},
  {id:51, type:"grammar", cat:"daily", text:"Neither of the two restaurants ___ open on Mondays.", correct:"is", distractors:["are","were","have been"], ex:"Neither of + 複數名詞，動詞視為單數，用 is。"},
  {id:52, type:"grammar", cat:"travel", text:"We need to find out ___ the local currency is worth.", correct:"how much", distractors:["how many","what","how"], ex:"詢問金額、價值用 how much。"},
  {id:53, type:"grammar", cat:"daily", text:"My phone needs ___; the screen is cracked.", correct:"fixing", distractors:["to fixing","fix","fixed"], ex:"need + Ving（主動形式表被動）等於 need to be fixed。"},
  {id:54, type:"grammar", cat:"travel", text:"Had I known about the strike, I ___ a different flight.", correct:"would have booked", distractors:["would book","will book","booked"], ex:"與過去事實相反的假設句（倒裝），主句用 would have + p.p.。"},
  {id:55, type:"grammar", cat:"daily", text:"She's the kind of person who always ___ her promises.", correct:"keeps", distractors:["keep","is keeping","kept"], ex:"先行詞 person 是第三人稱單數，關係子句動詞要配合用 keeps。"},
  {id:56, type:"grammar", cat:"travel", text:"Despite the heavy rain, the tour ___ ahead as planned.", correct:"went", distractors:["go","goes","has gone"], ex:"描述過去發生的事，用過去簡單式 went。"},
  {id:57, type:"grammar", cat:"daily", text:"Not only ___ late, but he also forgot his wallet.", correct:"was he", distractors:["he was","he is","is he"], ex:"Not only 放句首時，後面要倒裝，主詞和動詞對調。"},
  {id:58, type:"grammar", cat:"travel", text:"We'd better ___ a taxi instead of walking in this heat.", correct:"take", distractors:["to take","taking","took"], ex:"had better + 原形動詞，表示「最好…」。"},
  {id:59, type:"grammar", cat:"daily", text:"This book is ___ than the one I read last month.", correct:"far more interesting", distractors:["more interesting far","much interesting","far interesting"], ex:"far + 比較級用來加強語氣，表示「…得多」。"},
  {id:60, type:"grammar", cat:"travel", text:"The luggage ___ to the wrong carousel by mistake.", correct:"was sent", distractors:["sent","has sent","was sending"], ex:"行李是被「送」到錯誤轉盤，要用被動語態 was sent。"},
  {id:61, type:"grammar", cat:"daily", text:"I'd rather have stayed home than ___ to that boring party.", correct:"gone", distractors:["go","went","going"], ex:"would rather have + p.p. than (have) + p.p.，表達對過去的懊悔。"},
  {id:62, type:"grammar", cat:"travel", text:"Make sure your passport ___ for at least six months.", correct:"is valid", distractors:["valid","validates","will valid"], ex:"需要完整的 be 動詞 + 形容詞結構，valid 是形容詞。"},
  {id:63, type:"grammar", cat:"daily", text:"It's high time we ___ this old car.", correct:"replaced", distractors:["replace","will replace","are replacing"], ex:"it's (high) time + 子句用過去式，表示「該是…的時候了」。"},
  {id:64, type:"grammar", cat:"travel", text:"Few tourists ___ aware of the local customs before they arrive.", correct:"are", distractors:["is","was","has been"], ex:"Few tourists 是複數主詞，動詞要用 are。"},
  {id:65, type:"grammar", cat:"daily", text:"I can't help ___ how much things have changed.", correct:"noticing", distractors:["to notice","notice","noticed"], ex:"can't help + Ving 表示「忍不住…」。"},
  {id:66, type:"grammar", cat:"travel", text:"The flight attendant asked us ___ our seatbelts.", correct:"to fasten", distractors:["fastening","fasten","fastened"], ex:"ask someone to V 是常見的受詞補語句型。"},
  {id:67, type:"grammar", cat:"daily", text:"Hardly ___ the meeting started when his phone rang.", correct:"had", distractors:["did","has","was"], ex:"Hardly + had + 主詞 + p.p.，倒裝句表示「幾乎一…就…」。"},
  {id:68, type:"grammar", cat:"travel", text:"This is one of the most beautiful places I ___ ever visited.", correct:"have", distractors:["had","has","was"], ex:"one of the + 最高級 + 名詞 + (that) + 主詞 + have ever + p.p.，現在完成式表示「至今為止」。"},
  {id:69, type:"grammar", cat:"daily", text:"She seems ___ about the new project.", correct:"excited", distractors:["exciting","excite","to excite"], ex:"人對某事感到興奮，要用過去分詞形容詞 excited。"},
  {id:70, type:"grammar", cat:"travel", text:"Provided that the weather ___ fine, we'll go hiking tomorrow.", correct:"is", distractors:["will be","were","would be"], ex:"provided that 引導條件句，子句用現在式表示未來。"},
  {id:71, type:"grammar", cat:"daily", text:"He always insists on ___ for everyone when they go out.", correct:"paying", distractors:["pay","to pay","paid"], ex:"insist on + Ving，介系詞後面要接動名詞。"},
  {id:72, type:"grammar", cat:"travel", text:"The tour guide recommended that we ___ early to avoid the crowds.", correct:"arrive", distractors:["arrived","arriving","will arrive"], ex:"recommend that + 主詞 + 原形動詞（假設語氣），不受人稱與時態影響。"},
  {id:73, type:"grammar", cat:"daily", text:"I haven't finished the report yet — I ___ it by Friday though.", correct:"will have finished", distractors:["will finish","finish","am finishing"], ex:"未來完成式表示在未來某個時間點之前會完成的動作。"},
  {id:74, type:"grammar", cat:"travel", text:"Whoever ___ the lost passport, please hand it in at the front desk.", correct:"finds", distractors:["found","will find","is finding"], ex:"複合關係代名詞 whoever 引導的子句，描述一般情況用現在式。"},
  {id:75, type:"grammar", cat:"daily", text:"I'd appreciate it if you ___ keep this between us.", correct:"could", distractors:["can","will","would have"], ex:"I'd appreciate it if + 過去式助動詞，是禮貌且委婉的請求語氣。"},
  {id:76, type:"grammar", cat:"travel", text:"There's no point ___ for a table without a reservation on Saturday nights.", correct:"waiting", distractors:["to wait","wait","waited"], ex:"there's no point (in) + Ving，表示「…是沒有意義的」。"},
  {id:77, type:"grammar", cat:"daily", text:"The more you practice, ___ you'll become.", correct:"the more confident", distractors:["more confident","the most confident","much confident"], ex:"the + 比較級, the + 比較級 句型，前後結構要對稱。"},
  {id:78, type:"grammar", cat:"travel", text:"We were told that the museum ___ closed for renovations.", correct:"was", distractors:["is","has been","were"], ex:"主要子句是過去式 were told，依時態一致原則，子句也用過去式 was。"},
  {id:79, type:"grammar", cat:"daily", text:"Scarcely ___ sat down when the waiter came to take our order.", correct:"had we", distractors:["we had","did we","have we"], ex:"Scarcely + had + 主詞 + p.p. 是倒裝句，表示「幾乎一…就…」。"},
  {id:80, type:"grammar", cat:"travel", text:"It is essential that every passenger ___ their boarding pass ready.", correct:"have", distractors:["has","having","will have"], ex:"it is essential that + 主詞 + 原形動詞（假設語氣），不論主詞為何都用原形。"},

  // ---------- Phrase batch (81-120) ----------
  {id:81, type:"phrase", cat:"daily", text:"Could you fill me ___ on what happened at the meeting I missed?", correct:"in", distractors:["up","out","off"], ex:"fill someone in (on something) 表示「跟某人說明最新狀況」。"},
  {id:82, type:"phrase", cat:"travel", text:"We should look ___ the flight status before heading to the airport.", correct:"up", distractors:["into","over","after"], ex:"look up 表示「查詢資料」。"},
  {id:83, type:"phrase", cat:"daily", text:"I ___ into an old friend at the supermarket yesterday.", correct:"ran", distractors:["hit","fell","came"], ex:"run into someone 表示「偶然遇到某人」。"},
  {id:84, type:"phrase", cat:"travel", text:"Let's ___ along with the locals — they're really friendly here.", correct:"get", distractors:["come","hold","keep"], ex:"get along with 表示「與…相處融洽」。"},
  {id:85, type:"phrase", cat:"daily", text:"Could we ___ off the meeting until next week? I'm not ready.", correct:"put", distractors:["take","set","turn"], ex:"put off 表示「延後、拖延」。"},
  {id:86, type:"phrase", cat:"travel", text:"Don't ___ up on learning a few local phrases — it really helps.", correct:"give", distractors:["put","take","break"], ex:"give up on 表示「放棄」。"},
  {id:87, type:"phrase", cat:"daily", text:"I ___ across this great article while researching for work.", correct:"came", distractors:["went","got","looked"], ex:"come across 表示「偶然發現」。"},
  {id:88, type:"phrase", cat:"travel", text:"She really ___ after her mother — same smile and everything.", correct:"takes", distractors:["looks","gets","goes"], ex:"take after 表示「（外貌或個性）像家人」。"},
  {id:89, type:"phrase", cat:"daily", text:"He didn't ___ up to the party, so we left without him.", correct:"show", distractors:["stand","hold","keep"], ex:"show up 表示「出現、到場」。"},
  {id:90, type:"phrase", cat:"travel", text:"Our rental car ___ down in the middle of nowhere.", correct:"broke", distractors:["fell","ran","gave"], ex:"break down 表示「（車輛、機器）故障」。"},
  {id:91, type:"phrase", cat:"daily", text:"Take your time — there's no rush, we can ___ out the details later.", correct:"figure", distractors:["turn","set","bring"], ex:"figure out 表示「想出、弄清楚」。"},
  {id:92, type:"phrase", cat:"travel", text:"Our guide ___ up an interesting story about the old town's history.", correct:"brought", distractors:["took","gave","held"], ex:"bring up 表示「提起（話題）」。"},
  {id:93, type:"phrase", cat:"daily", text:"I had to ___ down the job offer — the salary was too low.", correct:"turn", distractors:["put","take","break"], ex:"turn down 表示「拒絕」。"},
  {id:94, type:"phrase", cat:"travel", text:"Could you ___ me up from the airport around 9 p.m.?", correct:"pick", distractors:["take","get","bring"], ex:"pick someone up 表示「去接某人」。"},
  {id:95, type:"phrase", cat:"daily", text:"Feel free to ___ by anytime — we're usually home in the evenings.", correct:"drop", distractors:["fall","step","set"], ex:"drop by 表示「順道拜訪」。"},
  {id:96, type:"phrase", cat:"travel", text:"It took her a while to ___ over the jet lag.", correct:"get", distractors:["come","go","break"], ex:"get over 表示「克服、恢復」。"},
  {id:97, type:"phrase", cat:"daily", text:"___ on a second, I just need to grab my keys.", correct:"Hold", distractors:["Keep","Stay","Set"], ex:"Hold on (a second) 是口語常用語，表示「稍等一下」。"},
  {id:98, type:"phrase", cat:"travel", text:"We decided to ___ on with our trip despite the rain.", correct:"carry", distractors:["bring","take","hold"], ex:"carry on (with) 表示「繼續進行」。"},
  {id:99, type:"phrase", cat:"daily", text:"If we're not careful with spending, we might ___ up broke by the end of the month.", correct:"end", distractors:["turn","bring","fall"], ex:"end up 表示「最終演變成某種結果」。"},
  {id:100, type:"phrase", cat:"travel", text:"You can always ___ on me if you need help with directions.", correct:"count", distractors:["focus","insist","agree"], ex:"count on 表示「依靠、信賴」。"},
  {id:101, type:"phrase", cat:"daily", text:"I'll ___ with this problem first thing tomorrow morning.", correct:"deal", distractors:["go","come","handle"], ex:"deal with 表示「處理」。"},
  {id:102, type:"phrase", cat:"travel", text:"It took the whole team a week to ___ up with a new itinerary.", correct:"come", distractors:["bring","get","make"], ex:"come up with 表示「想出（點子、方案）」。"},
  {id:103, type:"phrase", cat:"daily", text:"She's ___ through a really tough time at work lately.", correct:"going", distractors:["passing","running","coming"], ex:"go through 表示「經歷（困難）」。"},
  {id:104, type:"phrase", cat:"travel", text:"He felt dizzy and almost ___ out from the heat.", correct:"passed", distractors:["fell","gave","broke"], ex:"pass out 表示「昏倒」。"},
  {id:105, type:"phrase", cat:"daily", text:"We're planning to ___ off early to beat the morning traffic.", correct:"set", distractors:["take","turn","pull"], ex:"set off 表示「出發」。"},
  {id:106, type:"phrase", cat:"travel", text:"The driver had to ___ over because of the heavy fog.", correct:"pull", distractors:["set","get","turn"], ex:"pull over 表示「把車停到路邊」。"},
  {id:107, type:"phrase", cat:"daily", text:"The plane is scheduled to ___ off at 6 a.m. sharp.", correct:"take", distractors:["set","pull","get"], ex:"take off 表示飛機「起飛」。"},
  {id:108, type:"phrase", cat:"travel", text:"Don't forget to ___ off at the next stop — it's our station.", correct:"get", distractors:["pull","take","run"], ex:"get off 表示「下車」。"},
  {id:109, type:"phrase", cat:"daily", text:"We need to ___ on the next bus if we want to make it on time.", correct:"get", distractors:["pull","take","set"], ex:"get on 表示「上車、搭乘」。"},
  {id:110, type:"phrase", cat:"travel", text:"We're about to ___ out of cash — let's find an ATM.", correct:"run", distractors:["get","pull","go"], ex:"run out of 表示「用完、耗盡」。"},
  {id:111, type:"phrase", cat:"daily", text:"Could you ___ after my plants while I'm away?", correct:"look", distractors:["take","get","keep"], ex:"look after 表示「照顧」。"},
  {id:112, type:"phrase", cat:"travel", text:"What does this abbreviation on the ticket ___ for?", correct:"stand", distractors:["mean","look","go"], ex:"stand for 表示「代表、象徵」。"},
  {id:113, type:"phrase", cat:"daily", text:"Make sure to ___ up your files before the system update.", correct:"back", distractors:["set","pull","look"], ex:"back up 表示「備份」。"},
  {id:114, type:"phrase", cat:"travel", text:"The airline had to ___ off the flight due to the storm.", correct:"call", distractors:["set","turn","run"], ex:"call off 表示「取消」。"},
  {id:115, type:"phrase", cat:"daily", text:"Let me ___ you around the office before you start work.", correct:"show", distractors:["bring","set","look"], ex:"show someone around 表示「帶某人參觀」。"},
  {id:116, type:"phrase", cat:"travel", text:"A few of us went to the airport to ___ her off before her flight.", correct:"see", distractors:["take","bring","set"], ex:"see someone off 表示「為某人送行」。"},
  {id:117, type:"phrase", cat:"daily", text:"The pain medicine should ___ off in a few hours.", correct:"wear", distractors:["fade","run","die"], ex:"wear off 表示「（藥效、感覺）逐漸消退」。"},
  {id:118, type:"phrase", cat:"travel", text:"We decided to ___ to our original plan instead of changing the route.", correct:"stick", distractors:["go","stay","set"], ex:"stick to 表示「堅持、依照」。"},
  {id:119, type:"phrase", cat:"daily", text:"I need to ___ up on some sleep this weekend.", correct:"catch", distractors:["get","make","take"], ex:"catch up on 表示「補足（睡眠、進度等）」。"},
  {id:120, type:"phrase", cat:"travel", text:"After years of traveling, they finally decided to ___ down in one place.", correct:"settle", distractors:["set","stay","calm"], ex:"settle down 表示「安定下來、定居」。"},

  // ---------- Vocab batch (121-150) ----------
  {id:121, type:"vocab", cat:"daily", text:"Loud music can really ___ your ability to concentrate.", correct:"affect", distractors:["effect","effort","afford"], ex:"affect 是動詞「影響」，effect 通常作名詞「效果」，兩字常被搞混。"},
  {id:122, type:"vocab", cat:"travel", text:"Could you ___ me your phone charger for a few minutes?", correct:"lend", distractors:["borrow","rent","hire"], ex:"lend 是「借出」，borrow 是「借入」，方向相反，常被混用。"},
  {id:123, type:"vocab", cat:"daily", text:"I need to ___ my brother that I'll be late.", correct:"tell", distractors:["say","speak","talk"], ex:"tell 後面直接加人（tell + 人），say 不能直接加人。"},
  {id:124, type:"vocab", cat:"travel", text:"This neighborhood has several good restaurants within walking ___.", correct:"distance", distractors:["length","range","scope"], ex:"walking distance 是固定搭配，表示「步行可達的距離」。"},
  {id:125, type:"vocab", cat:"daily", text:"He's a very ___ person — always thinking about how others feel.", correct:"considerate", distractors:["considerable","considering","consideration"], ex:"considerate 表示「體貼的」，considerable 表示「相當大的（數量）」，兩字常混淆。"},
  {id:126, type:"vocab", cat:"travel", text:"Make sure you keep your ___ — it's needed for re-entry.", correct:"receipt", distractors:["recipe","reception","receive"], ex:"receipt（收據）與 recipe（食譜）拼字相近但意思完全不同。"},
  {id:127, type:"vocab", cat:"daily", text:"The new policy will ___ a significant impact on small businesses.", correct:"have", distractors:["do","make","take"], ex:"have an impact/effect on 是固定搭配，不能用 do / make / take 替換。"},
  {id:128, type:"vocab", cat:"travel", text:"We should exchange some money before the ___ rate changes.", correct:"exchange", distractors:["change","switch","trade"], ex:"exchange rate 是「匯率」的固定用語。"},
  {id:129, type:"vocab", cat:"daily", text:"I really ___ your help with the move last weekend.", correct:"appreciate", distractors:["thank","grateful","appreciation"], ex:"appreciate 是及物動詞，直接接受詞；thank 通常接人，grateful 是形容詞。"},
  {id:130, type:"vocab", cat:"travel", text:"We booked an ___ tour, so meals and activities are all covered.", correct:"all-inclusive", distractors:["all-included","all-inclusion","inclusive all"], ex:"all-inclusive 是固定用語，表示「包套全包式」。"},
  {id:131, type:"vocab", cat:"daily", text:"Please ___ the form and return it by Friday.", correct:"complete", distractors:["compete","complement","comply"], ex:"complete（填寫完成）與 compete（競爭）拼字相似但意思不同。"},
  {id:132, type:"vocab", cat:"travel", text:"The flight was delayed due to a technical ___.", correct:"issue", distractors:["issued","issuing","issuance"], ex:"issue 在此作名詞，表示「問題」。"},
  {id:133, type:"vocab", cat:"daily", text:"She gave a really ___ speech at the wedding.", correct:"touching", distractors:["touched","touch","touchy"], ex:"touching 表示「令人感動的」，touched 表示「（人）被感動的」，描述事物用 touching。"},
  {id:134, type:"vocab", cat:"travel", text:"Could you point out our hotel on the ___?", correct:"map", distractors:["plan","chart","scheme"], ex:"map 指地理地圖，plan 通常指建築平面圖或計畫。"},
  {id:135, type:"vocab", cat:"daily", text:"His explanation was so ___ that nobody understood it.", correct:"confusing", distractors:["confused","confuse","confusion"], ex:"confusing 描述「令人困惑的事物」，confused 描述「（人）感到困惑」。"},
  {id:136, type:"vocab", cat:"travel", text:"We need to ___ our flight at least 24 hours in advance.", correct:"check in for", distractors:["check in to","check out of","check on"], ex:"check in for a flight 是固定用法，表示「辦理登機手續」。"},
  {id:137, type:"vocab", cat:"daily", text:"I can't ___ the difference between these two shades of blue.", correct:"tell", distractors:["say","speak","know"], ex:"tell the difference 是固定搭配，表示「分辨出差異」。"},
  {id:138, type:"vocab", cat:"travel", text:"The hotel staff were incredibly ___ throughout our stay.", correct:"hospitable", distractors:["hospital","hospitalize","hospitality"], ex:"hospitable 是形容詞「好客的」，與 hospital（醫院）拼字相近但無關。"},
  {id:139, type:"vocab", cat:"daily", text:"It's important to stay ___ during long flights.", correct:"hydrated", distractors:["hydrate","hydration","hydrating"], ex:"stay hydrated 是固定片語，表示「保持水分充足」，hydrated 為形容詞用法。"},
  {id:140, type:"vocab", cat:"travel", text:"The museum is closed on ___ — plan your visit accordingly.", correct:"public holidays", distractors:["public holiday","publics holidays","public's holidays"], ex:"public holidays 為複數型態，指「國定假日」。"},
  {id:141, type:"vocab", cat:"daily", text:"He has a strong ___ for languages — he picks them up so fast.", correct:"aptitude", distractors:["attitude","altitude","aptly"], ex:"aptitude（天賦、資質）與 attitude（態度）拼字相近但意義不同。"},
  {id:142, type:"vocab", cat:"travel", text:"Don't forget to bring a universal power ___ for your devices.", correct:"adapter", distractors:["adopter","adaptor's","adapt"], ex:"adapter 指「轉接頭」，與 adopt（領養）字根不同，拼寫須留意。"},
  {id:143, type:"vocab", cat:"daily", text:"The meeting has been moved to a ___ time.", correct:"later", distractors:["latter","late","lately"], ex:"later 表示「較晚的（時間）」，latter 表示「後者」，常被混淆。"},
  {id:144, type:"vocab", cat:"travel", text:"There were ___ tourists than usual because of the off-season.", correct:"fewer", distractors:["less","little","few"], ex:"tourists 是可數名詞，須用 fewer，less 用於不可數名詞。"},
  {id:145, type:"vocab", cat:"daily", text:"The two reports are ___ identical, with only minor differences.", correct:"virtually", distractors:["virtual","virtue","virtuous"], ex:"virtually 是副詞，表示「幾乎、實際上」。"},
  {id:146, type:"vocab", cat:"travel", text:"Local customs ___ from region to region, so do some research first.", correct:"vary", distractors:["very","variety","variation"], ex:"vary 是動詞「不同、變化」，很容易與 very 拼字混淆。"},
  {id:147, type:"vocab", cat:"daily", text:"I'd like to ___ a complaint about the noise next door.", correct:"file", distractors:["fill","take","do"], ex:"file a complaint 是固定搭配，表示「提出投訴」。"},
  {id:148, type:"vocab", cat:"travel", text:"The view from the summit was absolutely ___.", correct:"breathtaking", distractors:["breathless","breathing","breath"], ex:"breathtaking 表示「令人屏息的、壯麗的」。"},
  {id:149, type:"vocab", cat:"daily", text:"Please keep your voice down — the baby is ___ asleep.", correct:"sound", distractors:["heavy","strong","deeply"], ex:"sound asleep 是固定片語，表示「熟睡」。"},
  {id:150, type:"vocab", cat:"travel", text:"The ferry departs ___ schedule every hour.", correct:"on", distractors:["in","by","at"], ex:"on schedule 表示「準時、按照時刻表」。"}
];
